### ISSUE TITLE
Clean UP & Dockerization eos6aun

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos6aun#4]

**Comment by samuelmaina** [comment]
HI @GemmaTuron , I have created a PR for the model.

**Comment by samuelmaina** [comment]
Fetch and tested  on eml successfully with each smiles producing an output.
`Fetch time 1070 seconds (0.3 hrs) `
- [eos6aun_cli_fetch.log](https://github.com/ersilia-os/eos6aun/files/11908033/eos6aun_cli_fetch.log)
- [Uploading eos6aun_cli_eml_pred.csv…]()
